
package us.kbase.featuresetutils;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: CalAveExpressionMatrixResult</p>
 * <pre>
 * average_expression_matrix_ref: generated average ExpressionMatrix object reference
 * report_name: report name generated by KBaseReport
 * report_ref: report reference generated by KBaseReport
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "average_expression_matrix_ref",
    "report_name",
    "report_ref"
})
public class CalAveExpressionMatrixResult {

    @JsonProperty("average_expression_matrix_ref")
    private String averageExpressionMatrixRef;
    @JsonProperty("report_name")
    private String reportName;
    @JsonProperty("report_ref")
    private String reportRef;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("average_expression_matrix_ref")
    public String getAverageExpressionMatrixRef() {
        return averageExpressionMatrixRef;
    }

    @JsonProperty("average_expression_matrix_ref")
    public void setAverageExpressionMatrixRef(String averageExpressionMatrixRef) {
        this.averageExpressionMatrixRef = averageExpressionMatrixRef;
    }

    public CalAveExpressionMatrixResult withAverageExpressionMatrixRef(String averageExpressionMatrixRef) {
        this.averageExpressionMatrixRef = averageExpressionMatrixRef;
        return this;
    }

    @JsonProperty("report_name")
    public String getReportName() {
        return reportName;
    }

    @JsonProperty("report_name")
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    public CalAveExpressionMatrixResult withReportName(String reportName) {
        this.reportName = reportName;
        return this;
    }

    @JsonProperty("report_ref")
    public String getReportRef() {
        return reportRef;
    }

    @JsonProperty("report_ref")
    public void setReportRef(String reportRef) {
        this.reportRef = reportRef;
    }

    public CalAveExpressionMatrixResult withReportRef(String reportRef) {
        this.reportRef = reportRef;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        return ((((((((("CalAveExpressionMatrixResult"+" [averageExpressionMatrixRef=")+ averageExpressionMatrixRef)+", reportName=")+ reportName)+", reportRef=")+ reportRef)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
