
package us.kbase.featuresetutils;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: UploadFeatureSetFromDiffExprResult</p>
 * <pre>
 * result_directory: folder path that holds all files generated by upload_featureset_from_diff_expr
 * up_feature_set_ref: generated upper FeatureSet object reference
 * down_feature_set_ref: generated down FeatureSet object reference
 * filtered_expression_matrix_ref: generated filtered ExpressionMatrix object reference
 * report_name: report name generated by KBaseReport
 * report_ref: report reference generated by KBaseReport
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "result_directory",
    "up_feature_set_ref",
    "down_feature_set_ref",
    "filtered_expression_matrix_ref",
    "report_name",
    "report_ref"
})
public class UploadFeatureSetFromDiffExprResult {

    @JsonProperty("result_directory")
    private String resultDirectory;
    @JsonProperty("up_feature_set_ref")
    private String upFeatureSetRef;
    @JsonProperty("down_feature_set_ref")
    private String downFeatureSetRef;
    @JsonProperty("filtered_expression_matrix_ref")
    private String filteredExpressionMatrixRef;
    @JsonProperty("report_name")
    private String reportName;
    @JsonProperty("report_ref")
    private String reportRef;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("result_directory")
    public String getResultDirectory() {
        return resultDirectory;
    }

    @JsonProperty("result_directory")
    public void setResultDirectory(String resultDirectory) {
        this.resultDirectory = resultDirectory;
    }

    public UploadFeatureSetFromDiffExprResult withResultDirectory(String resultDirectory) {
        this.resultDirectory = resultDirectory;
        return this;
    }

    @JsonProperty("up_feature_set_ref")
    public String getUpFeatureSetRef() {
        return upFeatureSetRef;
    }

    @JsonProperty("up_feature_set_ref")
    public void setUpFeatureSetRef(String upFeatureSetRef) {
        this.upFeatureSetRef = upFeatureSetRef;
    }

    public UploadFeatureSetFromDiffExprResult withUpFeatureSetRef(String upFeatureSetRef) {
        this.upFeatureSetRef = upFeatureSetRef;
        return this;
    }

    @JsonProperty("down_feature_set_ref")
    public String getDownFeatureSetRef() {
        return downFeatureSetRef;
    }

    @JsonProperty("down_feature_set_ref")
    public void setDownFeatureSetRef(String downFeatureSetRef) {
        this.downFeatureSetRef = downFeatureSetRef;
    }

    public UploadFeatureSetFromDiffExprResult withDownFeatureSetRef(String downFeatureSetRef) {
        this.downFeatureSetRef = downFeatureSetRef;
        return this;
    }

    @JsonProperty("filtered_expression_matrix_ref")
    public String getFilteredExpressionMatrixRef() {
        return filteredExpressionMatrixRef;
    }

    @JsonProperty("filtered_expression_matrix_ref")
    public void setFilteredExpressionMatrixRef(String filteredExpressionMatrixRef) {
        this.filteredExpressionMatrixRef = filteredExpressionMatrixRef;
    }

    public UploadFeatureSetFromDiffExprResult withFilteredExpressionMatrixRef(String filteredExpressionMatrixRef) {
        this.filteredExpressionMatrixRef = filteredExpressionMatrixRef;
        return this;
    }

    @JsonProperty("report_name")
    public String getReportName() {
        return reportName;
    }

    @JsonProperty("report_name")
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    public UploadFeatureSetFromDiffExprResult withReportName(String reportName) {
        this.reportName = reportName;
        return this;
    }

    @JsonProperty("report_ref")
    public String getReportRef() {
        return reportRef;
    }

    @JsonProperty("report_ref")
    public void setReportRef(String reportRef) {
        this.reportRef = reportRef;
    }

    public UploadFeatureSetFromDiffExprResult withReportRef(String reportRef) {
        this.reportRef = reportRef;
        return this;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        return ((((((((((((((("UploadFeatureSetFromDiffExprResult"+" [resultDirectory=")+ resultDirectory)+", upFeatureSetRef=")+ upFeatureSetRef)+", downFeatureSetRef=")+ downFeatureSetRef)+", filteredExpressionMatrixRef=")+ filteredExpressionMatrixRef)+", reportName=")+ reportName)+", reportRef=")+ reportRef)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
