
package us.kbase.featuresetutils;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: UploadFeatureSetFromDiffExprResult</p>
 * <pre>
 * result_directory: folder path that holds all files generated by upload_featureset_from_diff_expr
 * up_feature_set_ref_list: list of generated upper FeatureSet object reference
 * down_feature_set_ref_list: list of generated down FeatureSet object reference
 * filtered_expression_matrix_ref_list: list of generated filtered ExpressionMatrix object reference
 * report_name: report name generated by KBaseReport
 * report_ref: report reference generated by KBaseReport
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "result_directory",
    "up_feature_set_ref_list",
    "down_feature_set_ref_list",
    "filtered_expression_matrix_ref_list",
    "report_name",
    "report_ref"
})
public class UploadFeatureSetFromDiffExprResult {

    @JsonProperty("result_directory")
    private java.lang.String resultDirectory;
    @JsonProperty("up_feature_set_ref_list")
    private List<String> upFeatureSetRefList;
    @JsonProperty("down_feature_set_ref_list")
    private List<String> downFeatureSetRefList;
    @JsonProperty("filtered_expression_matrix_ref_list")
    private List<String> filteredExpressionMatrixRefList;
    @JsonProperty("report_name")
    private java.lang.String reportName;
    @JsonProperty("report_ref")
    private java.lang.String reportRef;
    private Map<java.lang.String, Object> additionalProperties = new HashMap<java.lang.String, Object>();

    @JsonProperty("result_directory")
    public java.lang.String getResultDirectory() {
        return resultDirectory;
    }

    @JsonProperty("result_directory")
    public void setResultDirectory(java.lang.String resultDirectory) {
        this.resultDirectory = resultDirectory;
    }

    public UploadFeatureSetFromDiffExprResult withResultDirectory(java.lang.String resultDirectory) {
        this.resultDirectory = resultDirectory;
        return this;
    }

    @JsonProperty("up_feature_set_ref_list")
    public List<String> getUpFeatureSetRefList() {
        return upFeatureSetRefList;
    }

    @JsonProperty("up_feature_set_ref_list")
    public void setUpFeatureSetRefList(List<String> upFeatureSetRefList) {
        this.upFeatureSetRefList = upFeatureSetRefList;
    }

    public UploadFeatureSetFromDiffExprResult withUpFeatureSetRefList(List<String> upFeatureSetRefList) {
        this.upFeatureSetRefList = upFeatureSetRefList;
        return this;
    }

    @JsonProperty("down_feature_set_ref_list")
    public List<String> getDownFeatureSetRefList() {
        return downFeatureSetRefList;
    }

    @JsonProperty("down_feature_set_ref_list")
    public void setDownFeatureSetRefList(List<String> downFeatureSetRefList) {
        this.downFeatureSetRefList = downFeatureSetRefList;
    }

    public UploadFeatureSetFromDiffExprResult withDownFeatureSetRefList(List<String> downFeatureSetRefList) {
        this.downFeatureSetRefList = downFeatureSetRefList;
        return this;
    }

    @JsonProperty("filtered_expression_matrix_ref_list")
    public List<String> getFilteredExpressionMatrixRefList() {
        return filteredExpressionMatrixRefList;
    }

    @JsonProperty("filtered_expression_matrix_ref_list")
    public void setFilteredExpressionMatrixRefList(List<String> filteredExpressionMatrixRefList) {
        this.filteredExpressionMatrixRefList = filteredExpressionMatrixRefList;
    }

    public UploadFeatureSetFromDiffExprResult withFilteredExpressionMatrixRefList(List<String> filteredExpressionMatrixRefList) {
        this.filteredExpressionMatrixRefList = filteredExpressionMatrixRefList;
        return this;
    }

    @JsonProperty("report_name")
    public java.lang.String getReportName() {
        return reportName;
    }

    @JsonProperty("report_name")
    public void setReportName(java.lang.String reportName) {
        this.reportName = reportName;
    }

    public UploadFeatureSetFromDiffExprResult withReportName(java.lang.String reportName) {
        this.reportName = reportName;
        return this;
    }

    @JsonProperty("report_ref")
    public java.lang.String getReportRef() {
        return reportRef;
    }

    @JsonProperty("report_ref")
    public void setReportRef(java.lang.String reportRef) {
        this.reportRef = reportRef;
    }

    public UploadFeatureSetFromDiffExprResult withReportRef(java.lang.String reportRef) {
        this.reportRef = reportRef;
        return this;
    }

    @JsonAnyGetter
    public Map<java.lang.String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(java.lang.String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        return ((((((((((((((("UploadFeatureSetFromDiffExprResult"+" [resultDirectory=")+ resultDirectory)+", upFeatureSetRefList=")+ upFeatureSetRefList)+", downFeatureSetRefList=")+ downFeatureSetRefList)+", filteredExpressionMatrixRefList=")+ filteredExpressionMatrixRefList)+", reportName=")+ reportName)+", reportRef=")+ reportRef)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
